apiVersion: batch/v1beta1
kind: CronJob
metadata:
  name: rallying-cry-calendar
spec:
  schedule: '*/5 * * * *'
  startingDeadlineSeconds: 600
  jobTemplate:
    spec:
      template:
        spec:
          containers:
            - name: rallying-cry-calendar-cron
              imagePullPolicy: Always
              image: registry.hub.docker.com/jcavanagh/rallying-cry-calendar:master
              args: []
          restartPolicy: OnFailure
