name: master

on:
  push:
    branches:
      - master

env:
  CI: true

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v1

      - name: Publish
        uses: elgohr/Publish-Docker-Github-Action@2.14
        with:
          name: jcavanagh/rallying-cry-calendar
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_TOKEN }}
          registry: registry.hub.docker.com
          tags: master
          snapshot: true
